### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Panchitor** [mbakholdina/srt-stats-plotting#4]
Install python version 7 and I still have the same problem.
copy python verification and error running.
pi@raspberrypi:/srt/srt-stats-plotting $ sudo python3.7 plot_srt_stats.py --is-sender /home/pi/Desktop/stats-rcv-lat0.csv
Traceback (most recent call last):
File "plot_srt_stats.py", line 5, in
import bokeh.io
ModuleNotFoundError: No module named 'bokeh'
pi@raspberrypi:/srt/srt-stats-plotting $ python3.7 -V
Python 3.7.0

**Comment by mbakholdina** [comment]
The script requires additional library dependencies to be installed. Please check `Requirements` section of readme. To install them run `pip install -r requirements.txt`.

**Comment by Panchitor** [comment]
Yes, I already have them installed.

What else can it be?

plot_srt_stats.py README.md requirements.txt
pi @ raspberrypi: ~ / srt / srt-stats-plotting $ sudo pip install -r requirements.txt
Requirement already satisfied: bokeh> = 1.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: pandas> = 0.24.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: Click> = 7.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: python-dateutil> = 2.1 in /usr/local/lib/python2.7/dist-packages (from bokeh> = 1.1.0 -> - r requirements.txt (line 1))
Requirement already satisfied: packaging> = 16.8 in /usr/local/lib/python2.7/dist-packages (from bokeh> = 1.1.0 -> - r requirements.txt (line 1))
Requirement already satisfied: tornado> = 4.3 in /usr/local/lib/python2.7/dist-packages (from bokeh> = 1.1.0 -> - r requirements.txt (line 1))
Requirement already satisfied: numpy> = 1.7.1 in /usr/lib/python2.7/dist-packages (from bokeh> = 1.1.0 -> - r requirements.txt (line 1))
Requirement already satisfied: PyYAML> = 3.10 in /usr/local/lib/python2.7/dist-packages (from bokeh> = 1.1.0 -> - r requirements.txt (line 1))
Requirement already satisfied: six> = 1.5.2 in /usr/lib/python2.7/dist-packages (from bokeh> = 1.1.0 -> - r requirements.txt (line 1))
Requirement already satisfied: futures> = 3.0.3 in /usr/local/lib/python2.7/dist-packages (from bokeh> = 1.1.0 -> - r requirements.txt (line 1))
Requirement already satisfied: Jinja2> = 2.7 in /usr/lib/python2.7/dist-packages (from bokeh> = 1.1.0 -> - r requirements.txt (line 1))
Requirement already satisfied: pillow> = 4.0 in /usr/lib/python2.7/dist-packages (from bokeh> = 1.1.0 -> - r requirements.txt (line 1))
Requirement already satisfied: pytz> = 2011k in /usr/local/lib/python2.7/dist-packages (from pandas> = 0.24.2 -> - r requirements.txt (line 2))
Requirement already satisfied: pyparsing> = 2.0.2 in /usr/local/lib/python2.7/dist-packages (from packaging> = 16.8-> bokeh> = 1.1.0 -> - r requirements.txt (line 1) )
Requirement already satisfied: singledispatch in /usr/local/lib/python2.7/dist-packages (from tornado> = 4.3-> bokeh> = 1.1.0 -> - r requirements.txt (line 1))
Requirement already satisfied: backports-abc> = 0.4 in /usr/local/lib/python2.7/dist-packages (from tornado> = 4.3-> bokeh> = 1.1.0 -> - r requirements.txt (line 1) )
Requirement already satisfied: MarkupSafe in /usr/lib/python2.7/dist-packages (from Jinja2> = 2.7-> bokeh> = 1.1.0 -> - r requirements.txt (line 1))
pi @ raspberrypi: ~ / srt / srt-stats-plotting $

**Comment by maxsharabayko** [comment]
@Panchitor Try to run 
`pip --version` Might be you are using `pip` for Python 2. In case case run with `pip3 install -r requirements.txt`.

**Comment by mbakholdina** [comment]
According to your logs, you installed the requirements for python2.7. To install the requirements for python3.7, follow the suggestion from @maxlovic. 

In order to avoid these problems in future, I suggest to use [virtual environments](https://realpython.com/python-virtual-environments-a-primer/) when running the scripts. The idea is to create a virtual environment for each particular project (script) with the version of python you need (python2 or python3) and all the dependencies. You may have as much virtual environments as you need with different set of dependencies and this will not affect your global python installation.

**Comment by Panchitor** [comment]
pi@raspberrypi:~/srt/srt-stats-plotting $ sudo pip3 install requirements.txt
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt

**Comment by Panchitor** [comment]
pi@raspberrypi:~/srt/srt-stats-plotting $ sudo pip3 install -r requirements.txt
Requirement already satisfied: bokeh>=1.1.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: Click>=7.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3/dist-packages (from bokeh>=1.1.0->-r requirements.txt (line 1))
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.5/dist-packages (from bokeh>=1.1.0->-r requirements.txt (line 1))
Requirement already satisfied: pillow>=4.0 in /usr/lib/python3/dist-packages (from bokeh>=1.1.0->-r requirements.txt (line 1))
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.5/dist-packages (from bokeh>=1.1.0->-r requirements.txt (line 1))
Requirement already satisfied: Jinja2>=2.7 in /usr/lib/python3/dist-packages (from bokeh>=1.1.0->-r requirements.txt (line 1))
Requirement already satisfied: numpy>=1.7.1 in /usr/lib/python3/dist-packages (from bokeh>=1.1.0->-r requirements.txt (line 1))
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.5/dist-packages (from bokeh>=1.1.0->-r requirements.txt (line 1))
Requirement already satisfied: tornado>=4.3 in /usr/local/lib/python3.5/dist-packages (from bokeh>=1.1.0->-r requirements.txt (line 1))
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.5/dist-packages (from pandas>=0.24.2->-r requirements.txt (line 2))
Requirement already satisfied: MarkupSafe in /usr/lib/python3/dist-packages (from Jinja2>=2.7->bokeh>=1.1.0->-r requirements.txt (line 1))
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.5/dist-packages (from packaging>=16.8->bokeh>=1.1.0->-r requirements.txt (line 1))
pi@raspberrypi:~/srt/srt-stats-plotting $ sudo python3.7 plot_srt_stats.py --is-sender /home/pi/Desktop/stats-rcv-lat0.csv
Traceback (most recent call last):
  File "plot_srt_stats.py", line 5, in <module>
    import bokeh.io
ModuleNotFoundError: No module named 'bokeh'

**Comment by maxsharabayko** [comment]
As you can see, pip3 installs the dependencies for python 3.5:
```
pip3 install -r requirements.txt
Requirement already satisfied: bokeh>=1.1.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1))
```
But then you run python 3.7:
```
sudo python3.7 plot_srt_stats.py --is-sender /home/pi/Desktop/stats-rcv-lat0.csv
```
So you need to solve this issue with paths on your system.

**Comment by Panchitor** [comment]
If I put it like this, this error throws me away.
pi @ raspberrypi: ~ / srt / srt-stats-plotting $ sudo python3.5 plot_srt_stats.py --is-sender /home/pi/Desktop/stats-rcv-lat0.csv
   File "plot_srt_stats.py", line 165
     print (f'fec_overhead: {sum_overhead}% ')
                                           ^
SyntaxError: invalid syntax

**Comment by Panchitor** [comment]
Thank you very much for the help I can already read the files.
Is it possible to have these reports online or only from files?
Thank you.

**Comment by mbakholdina** [comment]
Not sure what do you mean by having the report online. Could you please give more details?
The script relies on [bokeh library](https://bokeh.pydata.org/en/latest/) in order to plot and visualize the plots using web browser. Taking the .csv file with SRT stats, it actually parses this data, produces an .html file with the graphs nearby the .csv one and opens it in a default browser. At the very top of the page you will find a "Save" button which can be used for saving the graphs as .png files.

**Comment by Panchitor** [comment]
I wanted to know if you can see the statistics in real time, if there is any way that is updated every 1 or 2 seconds.

**Comment by mbakholdina** [comment]
No, it is not possible to do with the script. The idea is to perform an experiment using test application, get the stats from sender/receiver for a particular period of time say 2 minutes, and then create graphs from the stats .csv file in order to interpret the results. Any real-time statistics interpretation or visualization should be implemented at the application level, e.g. the encoder which uses SRT protocol as a transport might have a web-page with SRT statistics visualized in real-time like [Haivision Makito encoders](https://www.haivision.com/products/makito-series/) do.
