### ISSUE TITLE
Add .csv statistics file example

### ISSUE THREAD

**Issue by mbakholdina** [mbakholdina/srt-stats-plotting#7]
Add `.csv` statistics file example to be able to run the script and see the result quickly.

**Comment by koenkarsten** [comment]
I've been experimenting with this repo today, and I really like it! I'd like to submit an example .csv and .html as described in the issue, because I found that would've helped me with getting up and running ✌️

**Comment by koenkarsten** [comment]
Also included 1 paragraph on how to use this with `srt-live-transmit`

**Comment by mbakholdina** [comment]
Closing as a duplicate of #8.
